✏️ Improve redaction
devarops/jabalies pull request #1
Opened 2024-04-25 02:58 UTC by nepito

- [ ] Typo
- [ ] Make a new sentence

2024-04-25 03:28 UTC, devarops requested changes
Vamos poniendo cada oración en su propia línea.

2024-04-25 03:28 UTC, devarops commented on index.md
> +Somos una piara que corre hacia un futuro más saludable y feliz. Cada paso fortalece nuestro vínculo y nuestro compromiso compartido con el bienestar integral.
```suggestion
Somos una piara que corre hacia un futuro más saludable y feliz.
Cada paso fortalece nuestro vínculo y nuestro compromiso compartido con el bienestar integral.
```

2024-04-25 03:28 UTC, devarops commented on index.md
> +Somos una piara que corre hacia un futuro más saludable y feliz. Cada paso fortalece nuestro vínculo y nuestro compromiso compartido con el bienestar integral.
Pongamos cada oración en su propia línea.

2024-04-25 03:28 UTC, devarops commented on index.md
> +- [Instagram](https://www.instagram.com/jabalies_running_team_/)
Gracias

2024-04-25 03:28 UTC, devarops commented
@nepito Muchas gracias por tu revisión.

2024-04-27 15:55 UTC, devarops approved these changes
Gracias.

2024-04-27 15:55 UTC, merged

2024-04-28 04:45 UTC, nepito commented
Muchas gracias @devarops por aceptar el _pr_.